export const ADD_ADMIN_REQUEST='ADD_ADMIN_REQUEST'
export const ADD_ADMIN_SUCCESS='ADD_ADMIN_SUCCESS'
export const ADD_ADMIN_FAIL='ADD_ADMIN_FAIL'

export const UPDATE_ADMIN_REQUEST='UPDATE_ADMIN_REQUEST'
export const UPDATE_ADMIN_SUCCESS='UPDATE_ADMIN_SUCCESS'
export const UPDATE_ADMIN_FAIL='UPDATE_ADMIN_FAIL'

export const DELETE_ADMIN_REQUEST='DELETE_ADMIN_REQUEST'
export const DELETE_ADMIN_SUCCESS='DELETE_ADMIN_SUCCESS'
export const DELETE_ADMIN_FAIL='DELETE_ADMIN_FAIL'

export const ADMIN_LIST_REQUEST='ADMIN_LIST_REQUEST'
export const ADMIN_LIST_SUCCESS='ADMIN_LIST_SUCCESS'
export const ADMIN_LIST_FAIL='ADMIN_LIST_FAIL'

export const ADMIN_DETAILS_REQUEST='ADMIN_DETAILS_REQUEST'
export const ADMIN_DETAILS_SUCCESS='ADMIN_DETAILS_SUCCESS'
export const ADMIN_DETAILS_FAIL='ADMIN_DETAILS_FAIL'

export const ADMIN_COUNT_REQUEST='ADMIN_COUNT_REQUEST'
export const ADMIN_COUNT_SUCCESS='ADMIN_COUNT_SUCCESS'
export const ADMIN_COUNT_FAIL='ADMIN_COUNT_FAIL'
