export const ADD_BUS_REQUEST='ADD_BUS_REQUEST'
export const ADD_BUS_SUCCESS='ADD_BUS_SUCCESS'
export const ADD_BUS_FAIL='ADD_BUS_FAIL'

export const UPDATE_BUS_REQUEST='UPDATE_BUS_REQUEST'
export const UPDATE_BUS_SUCCESS='UPDATE_BUS_SUCCESS'
export const UPDATE_BUS_FAIL='UPDATE_BUS_FAIL'

export const DELETE_BUS_REQUEST='DELETE_BUS_REQUEST'
export const DELETE_BUS_SUCCESS='DELETE_BUS_SUCCESS'
export const DELETE_BUS_FAIL='DELETE_BUS_FAIL'

export const BUS_LIST_REQUEST='BUS_LIST_REQUEST'
export const BUS_LIST_SUCCESS='BUS_LIST_SUCCESS'
export const BUS_LIST_FAIL='BUS_LIST_FAIL'

export const BUS_DETAILS_REQUEST='BUS_DETAILS_REQUEST'
export const BUS_DETAILS_SUCCESS='BUS_DETAILS_SUCCESS'
export const BUS_DETAILS_FAIL='BUS_DETAILS_FAIL'

export const BUS_COUNT_REQUEST='BUS_COUNT_REQUEST'
export const BUS_COUNT_SUCCESS='BUS_COUNT_SUCCESS'
export const BUS_COUNT_FAIL='BUS_COUNT_FAIL'


