export const ADD_COMPLAINT_REQUEST='ADD_COMPLAINT_REQUEST'
export const ADD_COMPLAINT_SUCCESS='ADD_COMPLAINT_SUCCESS'
export const ADD_COMPLAINT_FAIL='ADD_COMPLAINT_FAIL'

export const UPDATE_COMPLAINT_REQUEST='UPDATE_COMPLAINT_REQUEST'
export const UPDATE_COMPLAINT_SUCCESS='UPDATE_COMPLAINT_SUCCESS'
export const UPDATE_COMPLAINT_FAIL='UPDATE_COMPLAINT_FAIL'

export const DELETE_COMPLAINT_REQUEST='DELETE_COMPLAINT_REQUEST'
export const DELETE_COMPLAINT_SUCCESS='DELETE_COMPLAINT_SUCCESS'
export const DELETE_COMPLAINT_FAIL='DELETE_COMPLAINT_FAIL'

export const COMPLAINT_LIST_REQUEST='COMPLAINT_LIST_REQUEST'
export const COMPLAINT_LIST_SUCCESS='COMPLAINT_LIST_SUCCESS'
export const COMPLAINT_LIST_FAIL='COMPLAINT_LIST_FAIL'

export const COMPLAINT_DETAILS_REQUEST='COMPLAINT_DETAILS_REQUEST'
export const COMPLAINT_DETAILS_SUCCESS='COMPLAINT_DETAILS_SUCCESS'
export const COMPLAINT_DETAILS_FAIL='COMPLAINT_DETAILS_FAIL'

export const COMPLAINT_COUNT_REQUEST='COMPLAINT_COUNT_REQUEST'
export const COMPLAINT_COUNT_SUCCESS='COMPLAINT_COUNT_SUCCESS'
export const COMPLAINT_COUNT_FAIL='COMPLAINT_COUNT_FAIL'


