export const ADD_DRIVER_REQUEST='ADD_DRIVER_REQUEST'
export const ADD_DRIVER_SUCCESS='ADD_DRIVER_SUCCESS'
export const ADD_DRIVER_FAIL='ADD_DRIVER_FAIL'

export const UPDATE_DRIVER_REQUEST='UPDATE_DRIVER_REQUEST'
export const UPDATE_DRIVER_SUCCESS='UPDATE_DRIVER_SUCCESS'
export const UPDATE_DRIVER_FAIL='UPDATE_DRIVER_FAIL'

export const DELETE_DRIVER_REQUEST='DELETE_DRIVER_REQUEST'
export const DELETE_DRIVER_SUCCESS='DELETE_DRIVER_SUCCESS'
export const DELETE_DRIVER_FAIL='DELETE_DRIVER_FAIL'

export const DRIVER_LIST_REQUEST='DRIVER_LIST_REQUEST'
export const DRIVER_LIST_SUCCESS='DRIVER_LIST_SUCCESS'
export const DRIVER_LIST_FAIL='DRIVER_LIST_FAIL'

export const DRIVER_DETAILS_REQUEST='DRIVER_DETAILS_REQUEST'
export const DRIVER_DETAILS_SUCCESS='DRIVER_DETAILS_SUCCESS'
export const DRIVER_DETAILS_FAIL='DRIVER_DETAILS_FAIL'

export const DRIVER_COUNT_REQUEST='DRIVER_COUNT_REQUEST'
export const DRIVER_COUNT_SUCCESS='DRIVER_COUNT_SUCCESS'
export const DRIVER_COUNT_FAIL='DRIVER_COUNT_FAIL'
