export const ADD_LICENSE_REQUEST='ADD_LICENSE_REQUEST'
export const ADD_LICENSE_SUCCESS='ADD_LICENSE_SUCCESS'
export const ADD_LICENSE_FAIL='ADD_LICENSE_FAIL'

export const UPDATE_LICENSE_REQUEST='UPDATE_LICENSE_REQUEST'
export const UPDATE_LICENSE_SUCCESS='UPDATE_LICENSE_SUCCESS'
export const UPDATE_LICENSE_FAIL='UPDATE_LICENSE_FAIL'

export const DELETE_LICENSE_REQUEST='DELETE_LICENSE_REQUEST'
export const DELETE_LICENSE_SUCCESS='DELETE_LICENSE_SUCCESS'
export const DELETE_LICENSE_FAIL='DELETE_LICENSE_FAIL'

export const LICENSE_LIST_REQUEST='LICENSE_LIST_REQUEST'
export const LICENSE_LIST_SUCCESS='LICENSE_LIST_SUCCESS'
export const LICENSE_LIST_FAIL='LICENSE_LIST_FAIL'

export const LICENSE_DETAILS_REQUEST='LICENSE_DETAILS_REQUEST'
export const LICENSE_DETAILS_SUCCESS='LICENSE_DETAILS_SUCCESS'
export const LICENSE_DETAILS_FAIL='LICENSE_DETAILS_FAIL'

export const LICENSE_COUNT_REQUEST='LICENSE_COUNT_REQUEST'
export const LICENSE_COUNT_SUCCESS='LICENSE_COUNT_SUCCESS'
export const LICENSE_COUNT_FAIL='LICENSE_COUNT_FAIL'
