export const ADD_PAYMENT_REQUEST='ADD_PAYMENT_REQUEST'
export const ADD_PAYMENT_SUCCESS='ADD_PAYMENT_SUCCESS'
export const ADD_PAYMENT_FAIL='ADD_PAYMENT_FAIL'

export const UPDATE_PAYMENT_REQUEST='UPDATE_PAYMENT_REQUEST'
export const UPDATE_PAYMENT_SUCCESS='UPDATE_PAYMENT_SUCCESS'
export const UPDATE_PAYMENT_FAIL='UPDATE_PAYMENT_FAIL'

export const DELETE_PAYMENT_REQUEST='DELETE_PAYMENT_REQUEST'
export const DELETE_PAYMENT_SUCCESS='DELETE_PAYMENT_SUCCESS'
export const DELETE_PAYMENT_FAIL='DELETE_PAYMENT_FAIL'

export const PAYMENT_LIST_REQUEST='PAYMENT_LIST_REQUEST'
export const PAYMENT_LIST_SUCCESS='PAYMENT_LIST_SUCCESS'
export const PAYMENT_LIST_FAIL='PAYMENT_LIST_FAIL'

export const PAYMENT_DETAILS_REQUEST='PAYMENT_DETAILS_REQUEST'
export const PAYMENT_DETAILS_SUCCESS='PAYMENT_DETAILS_SUCCESS'
export const PAYMENT_DETAILS_FAIL='PAYMENT_DETAILS_FAIL'
