export const ADD_ROUTE_REQUEST='ADD_ROUTE_REQUEST'
export const ADD_ROUTE_SUCCESS='ADD_ROUTE_SUCCESS'
export const ADD_ROUTE_FAIL='ADD_ROUTE_FAIL'

export const UPDATE_ROUTE_REQUEST='UPDATE_ROUTE_REQUEST'
export const UPDATE_ROUTE_SUCCESS='UPDATE_ROUTE_SUCCESS'
export const UPDATE_ROUTE_FAIL='UPDATE_ROUTE_FAIL'

export const DELETE_ROUTE_REQUEST='DELETE_ROUTE_REQUEST'
export const DELETE_ROUTE_SUCCESS='DELETE_ROUTE_SUCCESS'
export const DELETE_ROUTE_FAIL='DELETE_ROUTE_FAIL'

export const ROUTE_LIST_REQUEST='ROUTE_LIST_REQUEST'
export const ROUTE_LIST_SUCCESS='ROUTE_LIST_SUCCESS'
export const ROUTE_LIST_FAIL='ROUTE_LIST_FAIL'

export const ROUTE_DETAILS_REQUEST='ROUTE_DETAILS_REQUEST'
export const ROUTE_DETAILS_SUCCESS='ROUTE_DETAILS_SUCCESS'
export const ROUTE_DETAILS_FAIL='ROUTE_DETAILS_FAIL'

export const ROUTE_COUNT_REQUEST='ROUTE_COUNT_REQUEST'
export const ROUTE_COUNT_SUCCESS='ROUTE_COUNT_SUCCESS'
export const ROUTE_COUNT_FAIL='ROUTE_COUNT_FAIL'
