export const ADD_STUDENT_REQUEST='ADD_STUDENT_REQUEST'
export const ADD_STUDENT_SUCCESS='ADD_STUDENT_SUCCESS'
export const ADD_STUDENT_FAIL='ADD_STUDENT_FAIL'

export const UPDATE_STUDENT_REQUEST='UPDATE_STUDENT_REQUEST'
export const UPDATE_STUDENT_SUCCESS='UPDATE_STUDENT_SUCCESS'
export const UPDATE_STUDENT_FAIL='UPDATE_STUDENT_FAIL'

export const DELETE_STUDENT_REQUEST='DELETE_STUDENT_REQUEST'
export const DELETE_STUDENT_SUCCESS='DELETE_STUDENT_SUCCESS'
export const DELETE_STUDENT_FAIL='DELETE_STUDENT_FAIL'

export const STUDENT_LIST_REQUEST='STUDENT_LIST_REQUEST'
export const STUDENT_LIST_SUCCESS='STUDENT_LIST_SUCCESS'
export const STUDENT_LIST_FAIL='STUDENT_LIST_FAIL'

export const STUDENT_DETAILS_REQUEST='STUDENT_DETAILS_REQUEST'
export const STUDENT_DETAILS_SUCCESS='STUDENT_DETAILS_SUCCESS'
export const STUDENT_DETAILS_FAIL='STUDENT_DETAILS_FAIL'


